### ISSUE TITLE
Error 500 when uploading on Windows 

### ISSUE THREAD

**Issue by AndersonCeci** [OpenCovenant/ink#13]
While I was testing the code and uploaded a word file on Windows the console threw an error 500 as attached on the image,  but in Ubuntu works just fine 

![Capture](https://user-images.githubusercontent.com/37506005/177425951-cfa5e4d1-0dbe-4800-9d66-bce905b6c99d.PNG)

**Comment by AndiBraimllari** [comment]
Does this issue still occur?
